name: Pull Request

on:
  push:
    branches:
      - "*"

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install dependencies
        run: go mod download
      - name: Building
        run: go build -v ./...
      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.6.0
      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: v0.5.1
      - name: Run tests
        run: go test -v ./...